=== ImBadr/TP_XML_JSON_M1/TP_2_TADJER_ARRADI/exercice_1/carnet.xsd
<?xml version="1.0"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="contacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contact" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="type" type="xs:string" />
                            <xs:element name="lastname" type="xs:string" />
                            <xs:element name="firstname" type="xs:string" minOccurs="0" />
                            <xs:element name="phone" type="xs:long" />
                            <xs:element name="address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="street" type="xs:string" />
                                        <xs:element name="number" type="xs:string" />
                                        <xs:element name="city" type="xs:string" />
                                        <xs:element name="zip" type="xs:string" />
                                        <xs:element name="country" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ImBadr/TP_XML_JSON_M1/TP2/exercice_1/carnet.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="carnet.xsd">
    <contact>
        <type>Personne</type>
        <lastname>MOINEAU</lastname>
        <firstname>Philippe</firstname>
        <phone>+33699544532</phone>
        <address>
            <street>Avenue des écoles</street>
            <number>31bis</number>
            <city>Villepinte</city>
            <zip>93420</zip>
            <country>France</country>
        </address>
    </contact>

    <contact>
        <lastname>Credit Agricole</lastname>
        <type>Banque</type>
        <phone>0155545554</phone>
        <address>
            <street>Place de l'Hôtel-de-Ville</street>
            <number>8</number>
            <city>Garges-lès-Gonesse</city>
            <zip>95141 Cedex</zip>
            <country>France</country>
        </address>
    </contact>

    <contact>
        <type>Plombier</type>
        <lastname>RIVIERE</lastname>
        <firstname>Jean</firstname>
        <phone>0666995412</phone>
        <address>
            <street>Avenue du Versaille</street>
            <number>143</number>
            <city>Paris</city>
            <zip>75016</zip>
            <country>France</country>
        </address>
    </contact>
</contacts>
