=== ImBadr/TP_XML_JSON_M1/TP2/exercice_3/exo3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   
    <xs:complexType name="apply">    
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element name="plus" nillable="true"/>
                <xs:element name="times" nillable="true"/>
                <xs:element name="divide" nillable="true"/>
                <xs:element name="minus" nillable="true"/>
                <xs:element name="quotient" nillable="true"/>
            </xs:choice>

            <xs:choice minOccurs="2" maxOccurs="2">
                <xs:element name="apply" type="apply"/>
                <xs:element name="cn" type="xs:int"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="expressions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="apply" maxOccurs="unbounded" type="apply"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ImBadr/TP_XML_JSON_M1/TP_2_TADJER_ARRADI/exercice_3/exo3.xml
<?xml version="1.0" encoding="UTF-8"?>

<expressions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exo3.xsd">
    <apply >
        <plus/>
        <cn>2</cn>
        <cn>3</cn>
    </apply>

    <apply >
        <times/>
        <apply>
            <plus/>
            <cn>2</cn>
            <cn>3</cn>
        </apply>
        <cn>4</cn>
    </apply>

    <apply >
        <times/>
        <apply>
            <plus/>
            <cn>2</cn>
            <cn>3</cn>
        </apply>
        <cn>4</cn>
    </apply>
</expressions>
